# -*- coding: utf-8 -*-
"""Worksheet-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UuvqJRASrvANDAi_Az3vmww56f1cf4t
"""

# number 1 exapmple
import pandas as pd
# Creating a simple Series
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

import pandas as pd

series = pd.Series([10, 20, 30])
print(series.index)

series = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(series)

dates = pd.date_range('2023-01-01', periods=3)
series = pd.Series([10, 20, 30], index=dates)
print(series)
print(series.index)

# Set or Reset Index
series.index = ['x', 'y', 'z']  # Series

# For DataFrame
df = pd.DataFrame({'A': [1, 2]}, index=['row1', 'row2'])
df.reset_index(inplace=True)

import pandas as pd

# Sample DataFrame
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35],
'Salary': [50000, 60000, 70000]
}
df = pd.DataFrame(data)

# View the first two rows
print(df.head(2))

# View the last row
print(df.tail(1))

# DataFrame information
print(df.info())

# Summary statistics
print(df.describe())

# Check dimensions of the DataFrame
print(f"The DataFrame has {df.shape[0]} rows and {df.shape[1]} columns.")

# Access the 'Age' column
print(df['Age'])

# Select rows by numerical index
print(df.iloc[0])  # First row

# Select rows by condition
print(df.loc[df['Age'] > 30])  # Rows where Age > 30

# Task 1: Load dataset
import pandas as pd

# Replace 'bank.csv' with the correct path if needed
df = pd.read_csv("/content/drive/MyDrive/Dataset/bank.csv")
print("Dataset Loaded Successfully\n")

# Task 2: Check info and analyze object columns
print("DataFrame Info:")
print(df.info())
print("\n")

# (a) Columns with dtype=object
object_cols = df.select_dtypes(include='object').columns
print("Columns with object dtype:", list(object_cols))
print("\n")

# (b) Unique values of object columns
print("Unique values in object columns:")
for col in object_cols:
    print(f"{col}: {df[col].unique()}")
print("\n")

# (c) Total number of null values in each column
print("Null values in each column:")
print(df.isnull().sum())
print("\n")

# Task 3: Drop object columns and save new CSV
df_numeric = df.drop(columns=object_cols)
print("Columns with object dtype dropped.\n")

# Save numeric DataFrame to CSV
df_numeric.to_csv("banknumericdata.csv", index=False)
print("Numeric data saved to 'banknumericdata.csv'\n")

# Task 4: Read new CSV and find summary statistics
df_numeric_read = pd.read_csv("banknumericdata.csv")
print("Summary Statistics of Numeric Data:")
print(df_numeric_read.describe())

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/Dataset/Titanic-Dataset.csv")

# PROBLEM 2:
null_age_count = df['Age'].isnull().sum()
print("Null values in Age column:", null_age_count)

df = df.dropna(subset=['Age'])
print("Age null values removed.\n")

# PROBLEM 3:
embarked_dummies = pd.get_dummies(df['Embarked'], prefix='Embarked')

# Add new columns to DataFrame
df = pd.concat([df, embarked_dummies], axis=1)

# Drop original 'Embarked' column
df = df.drop('Embarked', axis=1)

# Show first few rows
print("Data after one-hot encoding:")
print(df.head(), "\n")

# PROBLEM 4:
survival_by_sex = df.groupby('Sex')['Survived'].mean()
print("Survival rate by Sex:")
print(survival_by_sex)

# Plot
survival_by_sex.plot(kind='bar')
plt.title("Survival Rate by Gender")
plt.xlabel("Gender")
plt.ylabel("Survival Rate")
plt.show()

# PROBLEM 5:
df['Embarked_port'] = embarked_dummies.idxmax(axis=1).str.replace("Embarked_", "")

survival_by_port = df.groupby('Embarked_port')['Survived'].mean()
print("\nSurvival rate by Embarked port:")
print(survival_by_port)

# Plot
survival_by_port.plot(kind='bar')
plt.title("Survival Rate by Embarkation Port")
plt.xlabel("Port")
plt.ylabel("Survival Rate")
plt.show()

df['Age_Group'] = pd.qcut(df['Age'], 5)

# Calculate mean survival by class and age group
survival_age_class = df.groupby(['Pclass', 'Age_Group'])['Survived'].mean()
print("\nSurvival by Pclass and Age Group:")
print(survival_age_class)

# Plot
survival_age_class.unstack().plot(kind='bar')
plt.title("Survival by Class and Age Group")
plt.xlabel("Passenger Class")
plt.ylabel("Survival Rate")
plt.show()